### ISSUE TITLE
No such file or directory: '../data/IEMOCAP_ASR/Ses01F_impro01_F000.htk'

### ISSUE THREAD

**Issue by FriedaSmith** [Kyoto-University-Speech-and-Audio/feng-ASR-SER#1]
I didn't find the code to generate `.htk`. Can you provide the code? And can you explain `the steps to run the repo`?

```
Traceback (most recent call last):
  File "/media/other/Code/SER/feng-asr-ser/preprocess/scripts_total.py", line 104, in <module>
    cpudat = load_dat(position)
  File "/media/other/Code/SER/feng-asr-ser/utils.py", line 30, in load_dat
    fh = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/IEMOCAP_ASR/Ses01F_impro01_F000.htk'
```

**Comment by fenghan96** [comment]
You could use HTK toolkit to make your own htk file.  Then use train.sh to train the model.

**Comment by wenku1992abc** [comment]
> 
> 
> You could use HTK toolkit to make your own htk file. Then use train.sh to train the model.

how to use HTK to generate my own htk file?
@fenghan96
